const USERS = [
  { user:'admin', pass:'123456', name:'Administrador', role:'Administrador' },
  { user:'supervisor', pass:'123456', name:'Supervisor', role:'Supervisor' },
  { user:'almacen1', pass:'123456', name:'Almacén 1', role:'Almacén' },
  { user:'almacen2', pass:'123456', name:'Almacén 2', role:'Almacén' },
  { user:'vendedor1', pass:'123456', name:'Vendedor 1', role:'Vendedor' },
  { user:'vendedor2', pass:'123456', name:'Vendedor 2', role:'Vendedor' },
  { user:'vendedor3', pass:'123456', name:'Vendedor 3', role:'Vendedor' },
  { user:'vendedor4', pass:'123456', name:'Vendedor 4', role:'Vendedor' },
  { user:'vendedor5', pass:'123456', name:'Vendedor 5', role:'Vendedor' }
];
const LS='retailos_stable_v1';
let state = load() || seed();
let currentUser = JSON.parse(sessionStorage.getItem('retailos_user')||'null');
let page = 'dashboard';
let search = '';
function seed(){return {products:[
  {sku:'100001',barcode:'100001',name:'COCINA BORD 4 HORNILLAS',brand:'BORD',model:'COC-4H',family:'Línea Blanca',stockSap:6,almacen:4,exhibicion:1,separado:1,observado:0,location:'LB-01'},
  {sku:'100002',barcode:'100002',name:'TV SAMSUNG 55 UHD',brand:'SAMSUNG',model:'UN55',family:'Televisores',stockSap:3,almacen:1,exhibicion:2,separado:0,observado:0,location:'TV-01'},
  {sku:'100003',barcode:'100003',name:'REFRIGERADORA LG NO FROST',brand:'LG',model:'NF300',family:'Línea Blanca',stockSap:2,almacen:0,exhibicion:1,separado:0,observado:1,location:'LB-02'},
  {sku:'100004',barcode:'100004',name:'LICUADORA OSTER CLÁSICA',brand:'OSTER',model:'OST4655',family:'Electro Pequeño',stockSap:10,almacen:8,exhibicion:2,separado:0,observado:0,location:'EP-01'},
], movements:[], separations:[], picking:[], dispatches:[], inventories:[], lastImport:null};}
function load(){try{return JSON.parse(localStorage.getItem(LS));}catch(e){return null}}
function save(){localStorage.setItem(LS,JSON.stringify(state));}
function money(n){return Number(n||0).toLocaleString('es-PE')}
function total(k){return state.products.reduce((s,p)=>s+Number(p[k]||0),0)}
function available(p){return Math.max(0, Number(p.stockSap||0)-Number(p.separado||0)-Number(p.observado||0));}
function app(html){document.getElementById('app').innerHTML=html; bindCommon();}
function bindCommon(){document.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page=b.dataset.page; render();}); const logout=document.getElementById('logout'); if(logout) logout.onclick=()=>{sessionStorage.removeItem('retailos_user'); currentUser=null; render();}}
function nav(){let items=['dashboard','productos','importar','movimientos','separaciones','picking','despachos','inventario','alertas','reportes']; let names={dashboard:'Dashboard',productos:'Productos',importar:'Importar SAP',movimientos:'Movimientos',separaciones:'Separaciones',picking:'Picking',despachos:'Despachos',inventario:'Inventario',alertas:'Alertas',reportes:'Reportes'}; return items.map(i=>`<button data-page="${i}" class="${page===i?'active':''}">${names[i]}</button>`).join('')}
function shell(content,title){app(`<div class="mobile-top">${nav()}<button id="logout">Salir</button></div><div class="layout"><aside class="side"><div class="logo"><div class="logo-mark">R</div><div><h2>RetailOS</h2><div class="role">${currentUser.name} · ${currentUser.role}</div></div></div><nav class="nav">${nav()}</nav><div style="position:absolute;bottom:20px;left:20px;right:20px"><button id="logout" class="secondary" style="width:100%">Cerrar sesión</button></div></aside><main class="main"><div class="top"><div><h1>${title}</h1><p class="hint">MVP estable para validación operativa en tienda</p></div><div class="hint">Usuario: <b>${currentUser.name}</b></div></div>${content}</main></div>`)}
function login(){app(`<div class="login"><div class="login-card"><div class="logo"><div class="logo-mark">R</div><div><h1>RetailOS</h1><p>MVP estable para validar en tienda</p></div></div><label>Usuario</label><input id="u" value="admin"><label>Contraseña</label><input id="p" type="password" value="123456"><div style="height:14px"></div><button id="btnLogin" style="width:100%">Ingresar</button><p class="hint">Usuarios demo: admin, supervisor, almacen1, almacen2, vendedor1 al vendedor5. Clave: 123456.</p><p id="err" style="color:#b91c1c;font-weight:bold"></p></div></div>`); document.getElementById('btnLogin').onclick=()=>{const u=document.getElementById('u').value.trim(); const p=document.getElementById('p').value; const user=USERS.find(x=>x.user===u&&x.pass===p); if(!user){document.getElementById('err').textContent='Usuario o clave incorrecta';return} currentUser=user; sessionStorage.setItem('retailos_user',JSON.stringify(user)); render();}}
function dashboard(){const critical=state.products.filter(p=>available(p)<=1).length; const sinUb=state.products.filter(p=>!p.location).length; shell(`<div class="cards"><div class="card"><div class="label">Stock SAP</div><div class="num">${money(total('stockSap'))}</div></div><div class="card"><div class="label">Almacén</div><div class="num">${money(total('almacen'))}</div></div><div class="card"><div class="label">Exhibición</div><div class="num">${money(total('exhibicion'))}</div></div><div class="card"><div class="label">Alertas</div><div class="num">${critical+sinUb}</div></div></div><div class="grid2"><div class="card"><h3 class="section-title">Últimos movimientos</h3>${state.movements.slice(-8).reverse().map(m=>`<div class="alert info"><b>${m.type}</b> · ${m.productName}<br><span class="hint">${m.qty} und · ${m.from||'-'} → ${m.to||'-'} · ${m.user} · ${new Date(m.date).toLocaleString()}</span></div>`).join('')||'<div class="empty">Sin movimientos registrados</div>'}</div><div class="card"><h3 class="section-title">Alertas rápidas</h3>${alertsList().slice(0,6).map(a=>`<div class="alert ${a.level}"><b>${a.title}</b><br><span class="hint">${a.text}</span></div>`).join('')||'<div class="empty">Sin alertas</div>'}</div></div>`, 'Dashboard')}
function productRows(){let q=search.toLowerCase(); return state.products.filter(p=>[p.sku,p.name,p.brand,p.model,p.family,p.location].join(' ').toLowerCase().includes(q));}
function productos(){shell(`<div class="toolbar"><input id="q" placeholder="Buscar por SKU, producto, marca, modelo o ubicación" value="${search}"><button id="newMove">Registrar movimiento</button><button id="reset" class="danger">Reiniciar demo</button></div><div class="table-wrap"><table><thead><tr><th>SKU</th><th>Producto</th><th>Familia</th><th>SAP</th><th>Almacén</th><th>Exhib.</th><th>Sep.</th><th>Obs.</th><th>Disp.</th><th>Ubicación</th></tr></thead><tbody>${productRows().map(p=>`<tr><td><b>${p.sku}</b></td><td>${p.name}<br><span class="hint">${p.brand||''} ${p.model||''}</span></td><td>${p.family||''}</td><td>${p.stockSap}</td><td>${p.almacen}</td><td>${p.exhibicion}</td><td>${p.separado}</td><td>${p.observado}</td><td><span class="badge ${available(p)<=0?'b-danger':available(p)==1?'b-warn':'b-ok'}">${available(p)}</span></td><td>${p.location||'<span class="badge b-danger">Sin ubicación</span>'}</td></tr>`).join('')}</tbody></table></div>`, 'Productos'); document.getElementById('q').oninput=e=>{search=e.target.value; productos()}; document.getElementById('newMove').onclick=()=>modalMovimiento(); document.getElementById('reset').onclick=()=>{if(confirm('¿Reiniciar datos demo?')){state=seed();save();render();}}}
function importar(){shell(`<div class="card"><h3>Importar archivo SAP</h3><p class="hint">Acepta .xls/.xlsx exportado desde SAP. También intenta leer archivos SAP en texto tabulado UTF-16.</p><input type="file" id="file" accept=".xls,.xlsx,.csv,.txt"><div style="height:12px"></div><button id="importBtn">Importar productos</button><p id="msg" class="hint"></p></div><div class="card" style="margin-top:16px"><h3>Última importación</h3><p>${state.lastImport?new Date(state.lastImport.date).toLocaleString()+' · '+state.lastImport.count+' productos':'Aún no se importó archivo'}</p></div>`, 'Importar SAP'); document.getElementById('importBtn').onclick=importFile;}
async function importFile(){const f=document.getElementById('file').files[0]; const msg=document.getElementById('msg'); if(!f){msg.textContent='Selecciona un archivo.'; return} msg.textContent='Leyendo archivo...'; try{let rows=[]; if(f.name.toLowerCase().endsWith('.xls')||f.name.toLowerCase().endsWith('.xlsx')){const data=await f.arrayBuffer(); try{const wb=XLSX.read(data,{type:'array'}); const ws=wb.Sheets[wb.SheetNames[0]]; rows=XLSX.utils.sheet_to_json(ws,{defval:''});}catch(e){const text=new TextDecoder('utf-16le').decode(data); rows=parseTabbed(text);} } else {const text=await f.text(); rows=parseTabbed(text);} const products=normalizeRows(rows); if(!products.length){msg.textContent='No se encontraron productos. Revisa si el archivo tiene columnas de artículo/descripcion/stock.'; return} state.products=products; state.lastImport={date:new Date().toISOString(),count:products.length}; save(); msg.textContent=`Importación correcta: ${products.length} productos cargados.`; setTimeout(()=>{page='productos'; render();},800);}catch(e){console.error(e); msg.textContent='Error al importar: '+e.message;}}
function parseTabbed(text){const lines=text.split(/\r?\n/).filter(x=>x.trim()); const sep=lines[0].includes('\t')?'\t':';'; const headers=lines[0].split(sep).map(h=>h.trim()); return lines.slice(1).map(line=>{const vals=line.split(sep); let o={}; headers.forEach((h,i)=>o[h]=vals[i]||''); return o;});}
function keyFind(obj, keys){const ks=Object.keys(obj); const clean=s=>String(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]/g,''); for(const wanted of keys){const w=clean(wanted); const k=ks.find(x=>clean(x).includes(w)); if(k) return obj[k];} return '';}
function toNum(v){return Number(String(v||'0').replace(/,/g,'').replace(/[^0-9.-]/g,''))||0;}
function normalizeRows(rows){const map=new Map(); for(const r of rows){const sku=String(keyFind(r,['articulo','material','codigo','sku','cod articulo'])).trim(); const name=String(keyFind(r,['descripcion','texto breve','producto','denominacion'])).trim(); if(!sku||!name) continue; const stock=toNum(keyFind(r,['stock libre','stock','cantidad','libre utilizacion','libre utilización'])); const brand=String(keyFind(r,['marca'])).trim(); const family=String(keyFind(r,['linea','familia','categoria','grupo articulos'])).trim(); const alm=String(keyFind(r,['almacen','almacén'])).trim(); const prev=map.get(sku)||{sku,barcode:sku,name,brand,model:'',family,stockSap:0,almacen:0,exhibicion:0,separado:0,observado:0,location:''}; prev.stockSap+=stock; const almLower=alm.toLowerCase(); if(almLower.includes('exh')||almLower.includes('exhib')) prev.exhibicion+=stock; else if(almLower.includes('obs')||almLower.includes('bloq')) prev.observado+=stock; else prev.almacen+=stock; if(!prev.location) prev.location=(family||'GEN').substring(0,2).toUpperCase()+'-01'; map.set(sku,prev);} return Array.from(map.values()).filter(p=>p.stockSap!==0);}
function modalMovimiento(){const opts=state.products.map(p=>`<option value="${p.sku}">${p.sku} · ${p.name}</option>`).join(''); document.body.insertAdjacentHTML('beforeend',`<div class="modal-bg" id="modal"><div class="modal"><h2>Registrar movimiento</h2><label>Producto</label><select id="mSku">${opts}</select><div class="row"><div><label>Origen</label><select id="mFrom"><option>Almacén</option><option>Exhibición</option><option>Separado</option><option>Observado</option></select></div><div><label>Destino</label><select id="mTo"><option>Exhibición</option><option>Almacén</option><option>Separado</option><option>Observado</option></select></div></div><label>Cantidad</label><input id="mQty" type="number" min="1" value="1"><label>Observación</label><textarea id="mObs"></textarea><div class="actions"><button class="secondary" onclick="closeModal()">Cancelar</button><button onclick="saveMove()">Guardar</button></div></div></div>`)}
window.closeModal=()=>document.getElementById('modal')?.remove();
window.saveMove=()=>{const sku=document.getElementById('mSku').value; const from=document.getElementById('mFrom').value; const to=document.getElementById('mTo').value; const qty=Number(document.getElementById('mQty').value||0); const p=state.products.find(x=>x.sku===sku); if(!p||qty<=0)return alert('Datos inválidos'); const fields={'Almacén':'almacen','Exhibición':'exhibicion','Separado':'separado','Observado':'observado'}; if((p[fields[from]]||0)<qty) return alert('No hay stock suficiente en origen'); p[fields[from]]-=qty; p[fields[to]]=(p[fields[to]]||0)+qty; state.movements.push({date:new Date().toISOString(),user:currentUser.name,type:'Movimiento interno',sku,productName:p.name,from,to,qty,obs:document.getElementById('mObs').value}); save(); closeModal(); render();}
function movimientos(){shell(`<div class="toolbar"><button id="newMove">Nuevo movimiento</button></div><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Usuario</th><th>Producto</th><th>Origen</th><th>Destino</th><th>Cant.</th></tr></thead><tbody>${state.movements.slice().reverse().map(m=>`<tr><td>${new Date(m.date).toLocaleString()}</td><td>${m.user}</td><td>${m.productName}</td><td>${m.from}</td><td>${m.to}</td><td>${m.qty}</td></tr>`).join('')}</tbody></table></div>`, 'Movimientos'); document.getElementById('newMove').onclick=()=>modalMovimiento();}
function separaciones(){shell(`<div class="card"><h3>Separar producto para cliente</h3><div class="row"><div><label>Producto</label><select id="sSku">${state.products.map(p=>`<option value="${p.sku}">${p.sku} · ${p.name}</option>`).join('')}</select></div><div><label>Cantidad</label><input id="sQty" type="number" value="1"></div></div><div class="row"><div><label>Cliente</label><input id="sClient" placeholder="Nombre del cliente"></div><div><label>Teléfono</label><input id="sPhone"></div></div><div style="height:12px"></div><button id="sBtn">Separar</button></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Fecha</th><th>Cliente</th><th>Producto</th><th>Cant.</th><th>Estado</th><th>Vendedor</th></tr></thead><tbody>${state.separations.slice().reverse().map(s=>`<tr><td>${new Date(s.date).toLocaleString()}</td><td>${s.client}<br><span class="hint">${s.phone}</span></td><td>${s.productName}</td><td>${s.qty}</td><td><span class="badge b-blue">${s.status}</span></td><td>${s.user}</td></tr>`).join('')}</tbody></table></div>`, 'Separaciones'); document.getElementById('sBtn').onclick=()=>{const sku=sSku.value, qty=Number(sQty.value||0), p=state.products.find(x=>x.sku===sku); if(!sClient.value.trim()) return alert('Ingresa cliente'); if(!p||p.almacen<qty) return alert('Stock insuficiente en almacén'); p.almacen-=qty; p.separado+=qty; const sep={id:Date.now(),date:new Date().toISOString(),client:sClient.value,phone:sPhone.value,sku,productName:p.name,qty,status:'Separado',user:currentUser.name}; state.separations.push(sep); state.picking.push({...sep,status:'Pendiente'}); state.movements.push({date:new Date().toISOString(),user:currentUser.name,type:'Separación',sku,productName:p.name,from:'Almacén',to:'Separado',qty}); save(); render();}}
function picking(){shell(`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Producto</th><th>Cant.</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${state.picking.slice().reverse().map((p,i)=>`<tr><td>${p.client}</td><td>${p.productName}</td><td>${p.qty}</td><td>${p.status}</td><td><button onclick="pickDone(${p.id})" ${p.status==='Recogido'?'disabled':''}>Marcar recogido</button></td></tr>`).join('')}</tbody></table></div>`, 'Picking')}
window.pickDone=(id)=>{const p=state.picking.find(x=>x.id===id); if(!p)return; p.status='Recogido'; p.picker=currentUser.name; state.dispatches.push({...p,status:'Pendiente despacho'}); state.movements.push({date:new Date().toISOString(),user:currentUser.name,type:'Picking recogido',sku:p.sku,productName:p.productName,from:'Separado',to:'Despacho',qty:p.qty}); save(); render();}
function despachos(){shell(`<div class="table-wrap"><table><thead><tr><th>Cliente</th><th>Producto</th><th>Cant.</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${state.dispatches.slice().reverse().map(d=>`<tr><td>${d.client}</td><td>${d.productName}</td><td>${d.qty}</td><td>${d.status}</td><td><button onclick="dispatchDone(${d.id})" ${d.status==='Entregado'?'disabled':''}>Entregar</button></td></tr>`).join('')}</tbody></table></div>`, 'Despachos')}
window.dispatchDone=(id)=>{const d=state.dispatches.find(x=>x.id===id); const p=state.products.find(x=>x.sku===d.sku); if(!d||!p)return; d.status='Entregado'; d.deliveredBy=currentUser.name; p.separado=Math.max(0,p.separado-d.qty); p.stockSap=Math.max(0,p.stockSap-d.qty); state.movements.push({date:new Date().toISOString(),user:currentUser.name,type:'Despacho entregado',sku:p.sku,productName:p.name,from:'Despacho',to:'Cliente',qty:d.qty}); save(); render();}
function inventario(){shell(`<div class="card"><h3>Conteo rápido</h3><div class="row"><div><label>Producto</label><select id="iSku">${state.products.map(p=>`<option value="${p.sku}">${p.sku} · ${p.name}</option>`).join('')}</select></div><div><label>Stock físico contado</label><input id="iQty" type="number" value="0"></div></div><div style="height:12px"></div><button id="iBtn">Guardar conteo</button></div><div class="table-wrap" style="margin-top:16px"><table><thead><tr><th>Fecha</th><th>Producto</th><th>Sistema</th><th>Físico</th><th>Diferencia</th><th>Usuario</th></tr></thead><tbody>${state.inventories.slice().reverse().map(i=>`<tr><td>${new Date(i.date).toLocaleString()}</td><td>${i.productName}</td><td>${i.system}</td><td>${i.physical}</td><td><span class="badge ${i.diff===0?'b-ok':'b-danger'}">${i.diff}</span></td><td>${i.user}</td></tr>`).join('')}</tbody></table></div>`, 'Inventario'); document.getElementById('iBtn').onclick=()=>{const p=state.products.find(x=>x.sku===iSku.value); const physical=Number(iQty.value||0); const system=p.almacen+p.exhibicion+p.separado+p.observado; state.inventories.push({date:new Date().toISOString(),sku:p.sku,productName:p.name,system,physical,diff:physical-system,user:currentUser.name}); save(); render();}}
function alertsList(){let arr=[]; for(const p of state.products){if(available(p)<=0) arr.push({level:'critical',title:'Sin disponible',text:`${p.name} no tiene stock disponible.`}); else if(available(p)===1) arr.push({level:'',title:'Última unidad',text:`${p.name} solo tiene 1 unidad disponible.`}); if(!p.location) arr.push({level:'critical',title:'Sin ubicación',text:`${p.name} no tiene ubicación asignada.`}); if(p.almacen===0&&p.exhibicion>0) arr.push({level:'',title:'Solo exhibición',text:`${p.name} está solo en exhibición.`}); if(p.observado>0) arr.push({level:'info',title:'Producto observado',text:`${p.name} tiene ${p.observado} unidad(es) observadas.`});} return arr;}
function alertas(){shell(`<div class="cards"><div class="card"><div class="label">Alertas totales</div><div class="num">${alertsList().length}</div></div><div class="card"><div class="label">Críticas</div><div class="num">${alertsList().filter(a=>a.level==='critical').length}</div></div><div class="card"><div class="label">Observados</div><div class="num">${total('observado')}</div></div><div class="card"><div class="label">Solo exhibición</div><div class="num">${state.products.filter(p=>p.almacen===0&&p.exhibicion>0).length}</div></div></div><div>${alertsList().map(a=>`<div class="alert ${a.level}"><b>${a.title}</b><br><span class="hint">${a.text}</span></div>`).join('')||'<div class="empty">Sin alertas</div>'}</div>`, 'Alertas')}
function reportes(){const byFamily={}; state.products.forEach(p=>byFamily[p.family||'Sin familia']=(byFamily[p.family||'Sin familia']||0)+p.stockSap); shell(`<div class="grid2"><div class="card"><h3>Stock por familia</h3><table>${Object.entries(byFamily).map(([k,v])=>`<tr><td>${k}</td><td><b>${v}</b></td></tr>`).join('')}</table></div><div class="card"><h3>Productividad</h3><p>Movimientos: <b>${state.movements.length}</b></p><p>Separaciones: <b>${state.separations.length}</b></p><p>Picking pendientes: <b>${state.picking.filter(p=>p.status!=='Recogido').length}</b></p><p>Despachos pendientes: <b>${state.dispatches.filter(d=>d.status!=='Entregado').length}</b></p></div></div>`, 'Reportes')}
function render(){if(!currentUser)return login(); ({dashboard,productos,importar,movimientos,separaciones,picking,despachos,inventario,alertas,reportes}[page]||dashboard)();}
render();
